Fix a compatibility issue with Python 3.8
